table Table
	lineageTag: 56d86698-c765-4700-a467-bd67d628cd9e

	column Fruit
		dataType: string
		lineageTag: d0e2cf79-516f-42d0-bf55-66749ff5ba21
		summarizeBy: none
		sourceColumn: Fruit

		annotation SummarizationSetBy = Automatic

	column 'Total Amount'
		dataType: int64
		formatString: 0
		lineageTag: 6cec9ec8-1418-4ffd-b2aa-2a46d5605f84
		summarizeBy: sum
		sourceColumn: Total Amount

		annotation SummarizationSetBy = Automatic

	column 'Total Qty'
		dataType: int64
		formatString: 0
		lineageTag: 9620f84c-0a72-493f-849f-c938a0f1036d
		summarizeBy: sum
		sourceColumn: Total Qty

		annotation SummarizationSetBy = Automatic

	partition Table = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WciwoyElV0lEyNjUAkUqxOtFKvol56flAnpkRSMwULOaUmAeEQK6hgQFI1EIpNhYA", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Fruit = _t, #"Total Amount" = _t, #"Total Qty" = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Fruit", type text}, {"Total Amount", Int64.Type}, {"Total Qty", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

